# Generated by Django 5.0.4 on 2024-05-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='isLiked',
        ),
    ]
