# Generated by Django 5.0.4 on 2024-05-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='created_at',
            new_name='date_time_created',
        ),
    ]
